### ISSUE TITLE
Closed Caption doesn't show on iOS

### ISSUE THREAD

**Issue by StephanieTM** [aws-samples/amazon-ivs-closed-captions-web-demo#12]
Hi, I'd like to report an issue.

- **A reproducible test case or series of steps**
Start the project and open it on an iPhone (I can reproduce it on iOS 16.1 Safari, Chrome, and Firefox).
The CC doesn't show at all.

- **The version of our code being used**
`master` branch (commit `f0a6cc13ef0ff1e51e68538d60da9adb33499bac`)

- **Any modifications you've made relevant to the bug**
None

- **Anything unusual about your environment or deployment**
None

I encountered this issue when using amazon-ivs-player but found little information about it. Any help would be appreciated.

**Comment by slee-aws** [comment]
Hello, thank you for this report. We have been able to reproduce the issue and are investigating.

**Comment by slee-aws** [comment]
@StephanieTM this issue should be resolved on the `master` branch. Note that on iOS, captioning is handled by the native iOS video controls and not all features may be available. More details are described in the [PlayerSDK Known Issues and Workarounds](https://docs.aws.amazon.com/ivs/latest/userguide/player-web.html#web-issues) page.

To use custom controls to enable and disable captions on iOS, you may want to consider using the [JWPlayer integration](https://docs.aws.amazon.com/ivs/latest/userguide/player-jwplayer.html) or [VideoJS integration](https://docs.aws.amazon.com/ivs/latest/userguide/player-videojs.html).
