### ISSUE TITLE
How captions are synced?

### ISSUE THREAD

**Issue by IronTony** [aws-samples/amazon-ivs-closed-captions-web-demo#6]
Hello,

I am trying to understand how the captions are synced with the video.
Moreover where are they? In a JSON file?
Could you help me understanding this please?

**Comment by mboulin** [comment]
Hi @IronTony !

The demo stream in this application has a closed captions track embedded inside the video stream. 
Amazon IVS supports closed captioning, provided they are transmitted in the right format (Amazon IVS accepts captions in line 21 CEA-708/EIA-608 format and in CC1 NTSC field 1.), and from the encoder sending the video to Amazon IVS (ex. OBS). You can read more about Closed Captioning with Amazon IVS here: [https://docs.aws.amazon.com/ivs/latest/userguide/streaming-config.html#streaming-config-captioning](https://docs.aws.amazon.com/ivs/latest/userguide/streaming-config.html#streaming-config-captioning).

If you are looking at automated captions, you might be interested in this demo, which uses Amazon Transcribe, and creates a sidecar WebVTT track on the client-side: [https://github.com/aws-samples/amazon-ivs-auto-captions-web-demo](https://github.com/aws-samples/amazon-ivs-auto-captions-web-demo)

**Comment by mboulin** [comment]
Closing this issue for now. Feel free to re-open if this didn't answer your question.
